name: Build and upload Docker image of dev branch to GHCR

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Upload Package to PyPI]
    types: [completed]

jobs:
  release-image:
    name: Build and upload Docker image of dev branch to GHCR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
