name: Remote tests

on:
  schedule:
    - cron: '0 12 * * *'  # 7 am EST every day

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  DailyRemoteTests:
    uses: ./.github/workflows/testing.yml
    with:
      pytest_markexpr: 'remote'
      os_list: '["windows-2022","windows-latest","macos-15-intel","macos-latest","ubuntu-latest"]'
      python_list: '["3.10","3.11","3.12","3.13"]'
    secrets:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  NotifyOnRemoteFailure:
    runs-on: ubuntu-latest
    needs: [ DailyRemoteTests ]
    if: ${{ always() && needs.DailyRemoteTests.result == 'failure' }}
    steps:
      - uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "CI Failure: nwb2bids Daily Tests (Remote)"
          to: cody.c.baker.phd@gmail.com  # Add more with comma separation (no spaces)
          from: nwb2bids
          body: "The daily tests (remote) workflow failed, please check status at https://github.com/con/nwb2bids/actions/workflows/daily_remote.yml"
