name: Deploy remote-only tests

on:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  RemoteTests:
    uses: ./.github/workflows/testing.yml
    with:
      pytest_markexpr: 'remote'
      os_list: '["windows-2022","windows-latest","macos-latest","ubuntu-latest"]'#"macos-15-intel" # TODO: re-add intel once bids-validator is fixed
      python_list: '["3.13"]'
    secrets:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
