name: Primary testing workflow

on:
  workflow_call:
    inputs:
      pytest_markexpr:
        description: 'Expression for pytest -m'
        required: false
        default: 'not remote'
        type: string
      os_list:
        description: 'JSON array of OS versions'
        required: true
        type: string
      python_list:
        description: 'JSON array of Python versions'
        required: true
        type: string

    secrets:
      CODECOV_TOKEN:
        required: true

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJson(inputs.os_list) }}
        python: ${{ fromJson(inputs.python_list) }}

    steps:
      - name: Set up environment
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install minimal dependencies (plus pytest)
        run: |
          python -m pip install --upgrade pip wheel
          pip install -e . pytest

      - name: Run minimal tests
        run: python -m pytest -m "not remote" -vv

      - if: runner.os == 'macOS'
        name: Temporary (12/10/25) - install deno on mac
        run: pip install deno

      - name: Install all dependencies
        run: pip install -e ".[all]" --group dev-all

      - if: ${{ inputs.pytest_markexpr == 'remote' }}
        name: Configure git for DataLad
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - if: runner.os == 'Windows'
        name: Enable long path support on Windows
        run: git config --global core.longpaths true

      - name: Run tests
        run: python -m pytest -m "${{ inputs.pytest_markexpr }}" -vv --cov=nwb2bids --cov-report xml:./codecov.xml
      - name: Upload full coverage to Codecov
        if: ${{ matrix.python == '3.13' && matrix.os == 'ubuntu-latest' }}
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./codecov.xml
          flags: unittests
          name: codecov-umbrella
          codecov_yml_path: ./codecov.yaml
          fail_ci_if_error: true
          verbose: true
