name: Primary testing workflow

on:
  workflow_call:
    inputs:
      pytest_markexpr:
        description: 'Expression for pytest -m'
        required: false
        default: 'not remote'
        type: string
      os_list:
        description: 'JSON array of OS versions'
        required: false
        default: '["windows-2022","windows-latest","macos-13","macos-latest","ubuntu-latest"]'
        type: string
      python_list:
        description: 'JSON array of Python versions'
        required: false
        default: '["3.10","3.11","3.12","3.13"]'
        type: string

    secrets:
      CODECOV_TOKEN:
        required: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJson(inputs.os_list) }}
        python: ${{ fromJson(inputs.python_list) }}

    steps:
      - name: Set up environment
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -e ".[all]" --group all

      - name: Run tests
        run: python -m pytest -m "${{ inputs.pytest_markexpr }}" -vv --cov=nwb2bids --cov-report xml:./codecov.xml
      - name: Upload full coverage to Codecov
        if: ${{ matrix.python == '3.13' && matrix.os == 'ubuntu-latest' }}
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./codecov.xml
          flags: unittests
          name: codecov-umbrella
          codecov_yml_path: ./codecov.yaml
          fail_ci_if_error: true
          verbose: true
